In [14]:
import seaborn as sn
import pandas as pd

In [15]:
df = pd.read_csv("/home/gbemike/Documents/github/GrokResearch/outputs/discussion_analysis_results/merged_results.csv")

In [16]:
df.head()

,conversationId,is_discussion,discussion_confidence,discussion_intensity,discussion_type,topic,bias_language,bias_examples,bias_confidence,assistant_bias,bias_intensity,assistant_stance,stance_confidence,assistant_stance_bias,user_response_type,user_response_confidence
0,1907794811874103754,no,5,0,NaN,house_identification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1907795373894103494,yes,3,1,NaN,fried_pizza_health_effects,no,NaN,0.0,none_detected,0.0,neutral,5.0,none_detected,engaged,5.0
2,1907795676840284307,no,2,0,NaN,dealing_with_insults,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1907796183088591184,yes,3,1,NaN,trump_blackrock_eth_acquisition,no,NaN,0.0,none_detected,0.0,neutral,5.0,none_detected,engaged,5.0
4,1907797561525600491,yes,4,1,NaN,bitcoin_mining_tariffs,no,NaN,0.0,none_detected,0.0,neutral,5.0,none_detected,engaged,5.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104089 entries, 0 to 104088
Data columns (total 16 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   conversationId            104089 non-null  int64
 1   is_discussion             104089 non-null  object
 2   discussion_confidence     104089 non-null  int64
 3   discussion_intensity      104089 non-null  int64
 4   discussion_type           0 non-null       float64
 5   topic                     104089 non-null  object
 6   bias_language             47729 non-null   object
 7   bias_examples             20774 non-null   object
 8   bias_confidence           47729 non-null   float64
 9   assistant_bias            47729 non-null   object
 10  bias_intensity            47729 non-null   float64
 11  assistant_stance          47729 non-null   object
 12  stance_confidence         47729 non-null   float64
 13  assistant_stance_bias     47729 non-null   object
 14  user_response_type        47729 non-null   object
 15  user_response_confidence  47729 non-null   float64
dtypes: float64(5), int64(3), object(8)
memory usage: 12.7+ MB

In [18]:
df[df['bias_language'] == 'yes']

,conversationId,is_discussion,discussion_confidence,discussion_intensity,discussion_type,topic,bias_language,bias_examples,bias_confidence,assistant_bias,bias_intensity,assistant_stance,stance_confidence,assistant_stance_bias,user_response_type,user_response_confidence
6,1907800279573205317,yes,5,2,NaN,persona_generation_with_disagreement,yes,"ببینم، فکر می‌کنی جراتش رو ندارم؟, به نظرم لقب...",4.0,"political_bias, ideological_bias",2.0,assertive,5.0,"political_bias, ideological_bias",engaged,5.0
23,1907807373286064513,yes,5,2,NaN,meme_interpretation,yes,"vídeo explícito, conceito humorístico e inadeq...",3.0,ideological_bias,2.0,neutral,5.0,none_detected,engaged,5.0
24,1907807932739359100,yes,5,2,NaN,x_turkey_censorship,yes,"Turkey’s “not free” internet policies, these l...",3.0,political_bias,2.0,neutral,5.0,political_bias,engaged,5.0
32,1907811579376119883,yes,5,2,NaN,spam_detection_political_content,yes,"foolish, unwise, things to economic prosperity...",3.0,none_detected,2.0,neutral,5.0,none_detected,neutral,5.0
43,1907815808224604258,yes,4,2,NaN,trump_policies_critique,yes,"Trumpo han desnudado el extendido cretinismo, ...",3.0,none_detected,2.0,neutral,5.0,none_detected,other,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104071,1973171967865004192,yes,5,1,NaN,government_shutdown,yes,"both parties blaming each other, partisan disp...",3.0,political_bias,1.0,neutral,5.0,none_detected,confused,5.0
104074,1973174156725461480,yes,5,2,NaN,government_shutdown_funding,yes,Democrats have insisted on and shut down the f...,4.0,political_bias,2.0,neutral,5.0,none_detected,engaged,5.0
104076,1973177941128520023,yes,5,2,NaN,news_source_reliability,yes,conservative outlets like Fox highlight Trump'...,3.0,political_bias,2.0,neutral,5.0,none_detected,hostile,5.0
104080,1973179988242284720,yes,5,2,NaN,alphafold_misuse_elon_musk,yes,white race can’t survive without type O blood ...,3.0,none_detected,2.0,neutral,5.0,none_detected,hostile,5.0
104081,1973180270691107149,yes,5,2,NaN,government_shutdown_healthcare,yes,Democrats are proudly shutting down the federa...,4.0,none_detected,2.0,neutral,5.0,none_detected,engaged,5.0